export { locations };

const locations = [
  "Aeroplane",
  "Bank",
  "Beach",
  "Theatre",
  "Casino",
  "Cathedral",
  "Circus Tent",
  "Corporate Party",
  "Crusader Army",
  "Wellness Centre",
  "Consulate",
  "Hospital",
  "Hotel",
  "Army Base",
  "Film Studio",
  "Ocean Liner",
  "Passenger Train",
  "Pirate Ship",
  "Polar Station",
  "Police Station",
  "Restaurant",
  "School",
  "Service Station",
  "Space Station",
];
