export { roles };

const roles = [
  [
    "First Class Passenger",
    "On-Board Security",
    "Serviceman",
    "Economy Class Passenger",
    "Flight Attendant",
    "Secondary Pilot",
    "Captain",
  ],
  [
    "Armoured Car Driver",
    "Manager",
    "Consultant",
    "Customer",
    "Robber",
    "Security Guard",
    "Clerk",
  ],
  [
    "Beach Waitress",
    "Kite Surfer",
    "Lifeguard",
    "Mugger",
    "Beach Goer",
    "Beach Photographer",
    "Ice Cream Van Driver",
  ],
  [
    "Coat Check Assistant",
    "Prompter",
    "Cash Assistant",
    "Visitor",
    "Director",
    "Actor",
    "Crewman",
  ],
  [
    "Publiucan",
    "Head Security Guard",
    "Muscle",
    "Manager",
    "Hustler",
    "Dealer",
    "Gambler",
  ],
  [
    "Priest",
    "Beggar",
    "Sinner",
    "Parishioner",
    "Tourist",
    "Sponsor",
    "Choir Singer",
  ],
  [
    "Acrobat",
    "Animal Trainer",
    "Magician",
    "Visitor",
    "Fire Eater",
    "Clown",
    "Juggler",
  ],
  [
    "Entertainer",
    "Manager",
    "Unexpected Guest",
    "Owner",
    "Secretary",
    "Accountant",
    "Delivery Boy",
  ],
  [
    "Monk",
    "Imprisoned Arab",
    "Servant",
    "Bishop",
    "Squire",
    "Archer",
    "Knight",
  ],
  [
    "Customer",
    "Stylist",
    "Masseuse",
    "Manicurist",
    "Make-Up Artist",
    "Dermatologist",
    "Cosmetologist",
  ],
  [
    "Security Guard",
    "Secretary",
    "Consul",
    "Government Official",
    "Tourist",
    "Refugee",
    "Diplomat",
  ],
  [
    "Nurse",
    "Doctor",
    "Anesthesiologist",
    "Intern",
    "Patient",
    "Therapist",
    "Surgeon",
  ],
  [
    "Concierge",
    "Security Guard",
    "Manager",
    "Lobby Boy",
    "Customer",
    "Publican",
    "Porter",
  ],
  [
    "Deserter",
    "Commander",
    "Field Doctor",
    "Soldier",
    "Sniper",
    "Officer",
    "Tank Engineer",
  ],
  [
    "Stunt Man",
    "Sound Engineer",
    "Camera Man",
    "Director",
    "Costume Artist",
    "Actor",
    "Producer",
  ],
  [
    "Wealthy Passenger",
    "Cook",
    "Captain",
    "Barman",
    "Musician",
    "Waiter",
    "Serviceman",
  ],
  [
    "Repairman",
    "Border Patrol",
    "Train Attendant",
    "Passenger",
    "Restaurant Chef",
    "Engineer",
    "Stoker",
  ],
  [
    "Cook",
    "Seaman",
    "Slave",
    "Cannoneer",
    "Bound Prisoner",
    "Cabin Boy",
    "Brave Captain",
  ],
  [
    "Field Doctor",
    "Geologist",
    "Expedition Leader",
    "Biologist",
    "Radioman",
    "Hydrologist",
    "Meteorologist",
  ],
  [
    "Detective",
    "Lawyer",
    "Journalist",
    "Criminalist",
    "Archivist",
    "Patrol Officer",
    "Criminal",
  ],
  [
    "Musician",
    "Customer",
    "Muscle",
    "Hostess",
    "Head Chef",
    "Food Critic",
    "Waiter",
  ],
  [
    "P.E. Teacher",
    "Student",
    "Headmaster",
    "Security Guard",
    "Cleaner",
    "Canteen Lady",
    "Repairman",
  ],
  [
    "Manager",
    "Tyre Specialist",
    "Biker",
    "Car Owner",
    "Car Wash Assistant",
    "Electrician",
    "Mechanic",
  ],
  [
    "Engineer",
    "Alien",
    "Space Tourist",
    "Pilot",
    "Commander",
    "Scientist",
    "Doctor",
  ],
  [
    "Cook",
    "Commander",
    "Sonar Technician",
    "Electronics Technician",
    "Seaman",
    "Radioman",
    "Navigator",
  ],
  [
    "Customer",
    "Cash Assistant",
    "Butcher",
    "Cleaner",
    "Security Guard",
    "Food Sample Hostess",
    "Shelf Stocker",
  ],
  [
    "Graduate Student",
    "Professor",
    "Dean",
    "Psychologist",
    "Repairman",
    "Student",
    "Cleaner",
  ],
  [
    "Ride Operator",
    "Parent",
    "Food Salesperson",
    "Cash Assistant",
    "Happy Child",
    "Annoying Child",
    "Teenager",
  ],
  [
    "Ticket Salesman",
    "Student",
    "Visitor",
    "Teacher",
    "Security Guard",
    "Painter",
    "Art Collector",
  ],
  [
    "Pastry Chef",
    "Visitor",
    "Taster",
    "Truffle Maker",
    "Taster",
    "Supply Worker",
    "Oompa Loompa",
  ],
  [
    "Judge",
    "Cat-Handler",
    "Animal Doctor",
    "Security Guard",
    "Cat Trainer",
    "Crazy Cat Lady",
    "Animal Lover",
  ],
  [
    "Priest",
    "Goth Girl",
    "Grave Robber",
    "Poet",
    "Mourner",
    "Gate Keeper",
    "Deceased Person",
  ],
  [
    "Safety Inspector",
    "Miner",
    "Supervisor",
    "Garbage Truck Assistant",
    "Driller",
    "Coordinator",
    "Blasting Enginner",
  ],
  [
    "Free Roaming Toddler",
    "Contractor",
    "Crane Driver",
    "Trespasser",
    "Safety Officer",
    "Electrician",
    "Enginner",
  ],
  [
    "Car Enthusiast",
    "Service Attendant",
    "Shopkeep",
    "Customer",
    "Car Washer",
    "Cash Assistant",
    "Customer",
  ],
  [
    "Dock Loader",
    "Salty Old Pirate",
    "Captain",
    "Seaman",
    "Smuggler",
    "Fisherman",
    "Exporter",
  ],
  [
    "Wrongly Accused Man",
    "CCTV Operator",
    "Guard",
    "Visitor",
    "Lawyer",
    "Cleaner",
    "Warden",
  ],
  [
    "Muscle",
    "Drummer",
    "Pianist",
    "Saxophonist",
    "Singer",
    "Jazz Fanatic",
    "Dancer",
  ],
  [
    "Elderly Man",
    "Journalist",
    "Author",
    "Volunteer",
    "Know It All",
    "Student",
    "Librarian",
  ],
  [
    "Regular Patron",
    "Publican",
    "Security Guard",
    "Dancer",
    "Courtesan",
    "Party Girl",
    "Model",
  ],
  [
    "Team Owner",
    "Racer",
    "Engineer",
    "Spectator",
    "Referee",
    "Mechanic",
    "Food Salesperson",
  ],
  [
    "Relative",
    "Cribbage Player",
    "Elderly Person",
    "Nurse",
    "Cleaner",
    "Cook",
    "Blind Person",
  ],
  ["Dancer", "Singer", "Fan", "Guitarist", "Drummer", "Roadie", "Stage Diver"],
  [
    "Elderly Man",
    "Lone Tourist",
    "Driver",
    "Annoying Child",
    "Tourist",
    "Tour Guide",
    "Photographer",
  ],
  [
    "Doctor",
    "Streaker",
    "Athlete",
    "Commentator",
    "Spectator",
    "Security Guard",
    "Referee",
  ],
  [
    "Tourist",
    "Train Driver",
    "Ticket Inspector",
    "Pregnant Lady",
    "Pickpocket",
    "Cleaner",
    "Businessman",
  ],
  [
    "Diplomat",
    "Interpreter",
    "Blowhard",
    "Tourist",
    "Napping Delegate",
    "Journalist",
    "Secretary Of State",
  ],
  [
    "Gardener",
    "Gourmet Guide",
    "Winemaker",
    "Exporter",
    "Butler",
    "Wine Taster",
    "Sommelier",
  ],
  [
    "Ring Bearer",
    "Groom",
    "Bride",
    "Officiant",
    "Photographer",
    "Bridesmaid",
    "Best Man",
  ],
  [
    "Zookeeper",
    "Visitor",
    "Photographer",
    "Child",
    "Animal Doctor",
    "Tourist",
    "Food Salesperson",
  ],
];
